apiVersion: v1
kind: Service
metadata:
  name: ftp-service
  namespace: etl-file-storage
spec:
  type: LoadBalancer
  ports:
    - name: ftp-port
      port: 21
      targetPort: 21
      protocol: TCP
    - name: ftp-data
      port: 20
      targetPort: 20
      protocol: TCP
    - name: ftp-passive-21100
      port: 21100
      targetPort: 21100
      protocol: TCP
    - name: ftp-passive-21101
      port: 21101
      targetPort: 21101
      protocol: TCP
    - name: ftp-passive-21102
      port: 21102
      targetPort: 21102
      protocol: TCP
    - name: ftp-passive-21103
      port: 21103
      targetPort: 21103
      protocol: TCP
    - name: ftp-passive-21104
      port: 21104
      targetPort: 21104
      protocol: TCP
    - name: ftp-passive-21105
      port: 21105
      targetPort: 21105
      protocol: TCP
    - name: ftp-passive-21106
      port: 21106
      targetPort: 21106
      protocol: TCP
    - name: ftp-passive-21107
      port: 21107
      targetPort: 21107
      protocol: TCP
    - name: ftp-passive-21108
      port: 21108
      targetPort: 21108
      protocol: TCP
    - name: ftp-passive-21109
      port: 21109
      targetPort: 21109
      protocol: TCP
    - name: ftp-passive-21110
      port: 21110
      targetPort: 21110
      protocol: TCP
  selector:
    app: ftp-server