apiVersion: v1
kind: PersistentVolume
metadata:
  name: ftp-pv
  namespace: etl-file-storage
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ftp-storage
  hostPath:
    path: /mnt/data